### ISSUE TITLE
Empty searchstrings dispatched under some circumstances?

### ISSUE THREAD

**Issue by bmschmidt** [Bookworm-project/BookwormGUI#30]
This may be something I'm doing wrong: but on one bookworm I recently build with the dev branch,
clicking on the lines seems to produce an empty call to the server rather than a sane bibliography query. 

Here's the URL: http://benschmidt.org/indexcatalog/

Sorry, don't have time to immediately debug more right now.

**Comment by organisciak** [comment]
That's because the API is giving an error, but not as JSON (while the GUI tries to parse JSON). That will be better handled with updated JSON responses in BookwormDB.

Here's the error the API gives, which JSON.parse chokes on by the very first character:

```
<!--: spam
Content-Type: text/html

<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> -->
<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> --> -->
</font> </font> </font> </script> </object> </blockquote> </pre>
</table> </table> </table> </table> </table> </font> </font> </font><pre>Traceback (most recent call last):
  File "/usr/lib/cgi-bin/dbbindings.py", line 54, in &lt;module>
    main(JSONinput)
  File "/usr/lib/cgi-bin/dbbindings.py", line 40, in main
    print p.execute()
  File "/home/bschmidt/bookwormDB/bookwormDB/general_API.py", line 301, in execute
    return query.execute()
  File "/home/bschmidt/bookwormDB/bookwormDB/SQLAPI.py", line 967, in execute
    value = getattr(self,self.method)()
  File "/home/bschmidt/bookwormDB/bookwormDB/SQLAPI.py", line 851, in return_books
    silent = self.cursor.execute(self.bibliography_query())
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'searchstring' in 'field list'")
</pre>
```

Is 'searchstring' indexed? Seems to be a Mysql error.

**Comment by bmschmidt** [comment]
Yeah you're right. Sorry to bother. For some reason my Chrome network activity was looking wrong.
